// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Store_Unit2.Models;

#nullable disable

namespace Store_Unit2.Migrations
{
    [DbContext(typeof(ProductContext))]
    [Migration("20241020011125_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.35")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Store_Unit2.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Meet the iTable, the most intelligent piece of furniture ever created. It's not just a table, it's a lifestyle upgrade. Equipped with revolutionary \"Surface Stability\" technology, the iTable supports all your belongings without breaking a sweat. With a sleek, minimalist design, it's perfect for working, dining, or just admiring. Need more? It comes with \"Zero Charging Ports\" for the ultimate wireless experience and never requires updates.",
                            ImagePath = "/images/ITable.png",
                            Name = "iTable",
                            Price = 499.0
                        },
                        new
                        {
                            Id = 2,
                            Description = "Introducing the revolutionary Air Pro – the world’s most advanced pillow. With cutting-edge \"cloud-like\" technology, this pillow offers the ultimate blend of softness and support, making you feel like you're sleeping on air (because you practically are). Engineered with our patented \"Fluff Dynamics,\" the Air Pro adjusts seamlessly to your sleep posture. Plus, it’s so lightweight, you’ll forget it’s even there. Rest easy, dream big, and prepare to elevate your naps to a whole new level of comfort.",
                            ImagePath = "/images/AirPro.png",
                            Name = "Air Pro",
                            Price = 19999.0
                        },
                        new
                        {
                            Id = 3,
                            Description = "The Dice Pro is here to redefine the world of decision-making. Say goodbye to the era of uncertainty with this sleek, precision-engineered tool. Crafted from premium polycarbonate, the Dice Pro offers a smooth, satisfying roll every time, ensuring your fate is left in the hands of the finest randomness known to humankind. Need to choose a restaurant? Figure out who's driving? The Dice Pro has your back, delivering unparalleled performance with every roll.",
                            ImagePath = "/images/DicePro.png",
                            Name = "Dice Pro",
                            Price = 399.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
